version: '3.0'
services:
  db:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "challenge"
      POSTGRES_DB: "challenge"
  api:
    build: .
    command: gunicorn djangochallenge.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db