version: '3.0'
services:
  db:
    image: postgres:12
    ports:
      - "5342:5342"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
  api:
    build:
      context: .
      target: dev
    command: sh -c "./wait-for-it.sh db:5432 && python3 manage.py migrate && python3
      manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
