# Generated by Django 3.1.5 on 2021-11-14 21:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.TextField(verbose_name='name')),
                ('picture', models.URLField(verbose_name='picture')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('category', models.TextField(verbose_name='category')),
                ('title', models.TextField(verbose_name='title')),
                ('summary', models.TextField(verbose_name='summary')),
                ('firstParagraph', models.TextField(verbose_name='firstParagraph')),
                ('body', models.TextField(verbose_name='body')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.author')),
            ],
        ),
    ]
